name: Test

on: workflow_dispatch

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.17