name: deploy code on EC2

on: workflow_dispatch

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install VPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          echo "${{secrets.HAWKS_BAY_OVPN}}" > client.ovpn
          pwd
          ls

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: /home/runner/work/movie-recommender-system/movie-recommender-system/client.ovpn

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.17